site_name: linq - LINQ for C++
site_url: https://dervis.de/linq
repo_url: https://github.com/cemdervis/linq
repo_name: cemdervis/linq
copyright: Copyright &copy; 2015 - 2025 Cem Dervis
theme:
  name: material
  logo: img/icon.png
  font:
    text: Nunito Sans
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.sections
    - navigation.footer
    - navigation.path
    - navigation.expand
    - content.code.copy
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/solid/house-chimney
      link: https://dervis.de
      name: Cem Dervis
    - icon: fontawesome/brands/github
      link: https://github.com/cemdervis/linq
plugins:
  - search
  - offline
markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js